### ISSUE TITLE
[BUG] [GAMEBOARD] Adding a new floor causes grid area to go white, and floor is never created

### ISSUE THREAD

**Issue by FuzzySadist** [Kruptein/PlanarAlly#1015]
**Describe the bug**
Adding a new floor causes grid area to go white, and floor is never created

**To Reproduce**
1. Click on floor icon
2. Click on 'add new floor'
3. Enter a name for the floor
4. Click "Submit"

**Expected behavior**
A new floor is added

**Actual behavior**
New floor is not added
Entire 'grid area' goes white, bottom left buttons disappear.
Upon refresh no floor was added

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by FuzzySadist** [comment]
![Screenshot 2022-08-08 214847](https://user-images.githubusercontent.com/8291885/183566833-6d4a49d2-e25b-40d2-b029-58ed987eabbb.png)

**Comment by Kruptein** [comment]
Fixed in gameboard server version 1.16.

Just to make you aware, the board version of PA has some performance improvement things enabled, one of which is that other floors are not rendered while not on them.  This is something that I still need to investigate whether I can make it run smooth enough with other floors visible.
