### ISSUE TITLE
[VIRUS?] Kaspersky reported PlanarAllyServer.exe as virus.

### ISSUE THREAD

**Issue by cusppi** [Kruptein/PlanarAlly#1080]
I downloaded last build (2022.2.3 for windows) and when i unzipped the file  Kaspersky reported PlanarAllyServer.exe file (both inside and outside dist folder) as Trojan-Ransom.Win64.Alien.df and deleted them.
Checking both exe files and zip file on Virustotal and it seems that other three AV reported as virus.

**Comment by Kruptein** [comment]
You're the second person this week to bring this up, guess Kaspersky recently updated their definitions.

It's more than likely a false-positive given that it's build entirely in an isolated environment with tools that are commonly used, but I get the hesitance.

This is most likely due to some actual virus also using pyinstaller, the tool responsible for packaging the python code to an .exe file.

That said, I'll check if there is a newer version of pyinstaller to see if that resolves the issue.
I might also look into upgrading the windows CI environment that the exe is built in.

**Comment by Kruptein** [comment]
After 2 days of trying some different parameters and stuff, I dropped PyInstaller in favor of nuitka, as the former keeps falsely getting flagged by some antivirus vendors out there. The best thing is that depending on the parameters a different set of vendors flags it (always about 7 from 71 tested).

The big downside to using nuitka is that instead of a minute it takes 15 minutes to build the exe. I guess for now that this is fine, given that I don't release that often.

It will be part of the upcoming 2022.3 release
