### ISSUE TITLE
Trouble with the FoW and Light

### ISSUE THREAD

**Issue by freddyyeddy** [Kruptein/PlanarAlly#149]
Either Im having trouble with the FoW and its just buggy. Or im doing it wrong. The Documentation is little help. Im trying to see where I can change the view distance of a player token or where i can create a light source. I found out you can use the aura option for a light source but for the players to "see" with the light source then it has to be on the token layer and clutters their interface up.  If I use their tokens aura as the light source and give them object permissions (so they can move it themselves) they can change the attribute.  Maybe we need DM only settings On Tokens that have like view distance and move distance. I would also love to let my players see each others "Light". So Maybe the solution wold to add a Player Config Tab For the DM. Another Issue I see is that the players can just move their tokens around any distance which defeats the FoW if thew can use their token as a flash light before placing it. Perhaps allow configurable max player move distance too?

**Comment by Kruptein** [comment]
Hey, Sorry that the documentation is not super clear yet, it's a one man project and I don't always have all the time to allocate, but I know it's not there yet.

Up until now I've always ran with the rationale that players are there to have fun and thus don't want to spoil themselves / ruin the fun. Hence the ability for players to currently change their vision aura's and/or move as far as they can.

I can see why this can be an issue in some groups, so I'll try to pick this up as a todo. (I do have a lot of feature requests though, so I'll have to prioritize a bit)

That said, it's totally possible currently to have players see each-other's lights.  If you're looking at a token configuration dialog and add a new aura, you make it a light with the 'lightbulb' icon (so that it stops against walls etc) and you can share the aura with the 'eye' icon.

**Comment by freddyyeddy** [comment]
Thanks for the info I will close this issue.
