### ISSUE TITLE
Fog of War and Painted Lines Issues

### ISSUE THREAD

**Issue by freddyyeddy** [Kruptein/PlanarAlly#157]
When drawing the outline of a map areas with the paint tool the lines made block light like expected but the end points are connected with a straight line. So If i am drawing a half circle for example around a cavern to block movement and Line of Sight Light the line connecting the end points of the line will cut off half of the area and block movement and light. As a work around i have been having to draw the outline and circle back to the start point to avoid this issue.

**Comment by Kruptein** [comment]
This is indeed a current limitation of the paint tool, that said the paint tool is not getting much attention currently because it's a bit suboptimal performance wise.
You could use the polygon tool instead which gives you precise control over the vision lines.
(you left click where you want a point and right click to finish the polygon which will connect the start and end lines)
I personally use the polygon tool for everything circle related, but I can understand the desire to use the paint tool out of ease of use

**Comment by Kruptein** [comment]
Since release 0.18.0, the polygon tool got a toggle to decide whether to automatically close the shape or not, so this issue should be resolved by now.
