### ISSUE TITLE
Weirdness with the zoom, camera position and changing locations

### ISSUE THREAD

**Issue by Daniferrito** [Kruptein/PlanarAlly#176]
I found this bug when writing code for the "move shapes to other locations" tool.

To reproduce: Have two locations, and at least a shape in each location in view (so you can see the position of the camera with respect to something).
Just changing location works normally. Zoom and camera position stay unique for each location. However, when the position of the camera is changed, and then the location is changed to the other location and back, once coming back the zoom will be diferent from the previous one, and the location of the object in the camera will have changed (looking at raw coordinates, it seems like the absolute position of the camera is preserved correctly, but the new zoom makes the shape shift in the camera, as the position of the camera is references to the top-left of the camera).

Most of this reasoning might be wrong, as I still dont understaund exactly the position representation in PlanarAlly, diferences between local and global points, and when each one is used.

**Comment by Kruptein** [comment]
I've also noticed this myself and this must be a bug I've introduced recently. (I also introduced a bug with initiatives that I'm working on)

The coordinate system is actually rather easy.  the global coordinates is what should be used in most cases, it means the same across all different clients and must be used when communicating with the server to ensure that everything is in the same format.

The local coordinates come in only when something has to be displayed on the screen, so in practice only in code related to drawing on the canvas.  This is because every client's camera settings will be different (pan and zoom).  These local coordinates can be calculated based on the pan/zoom in combination with the global coord.
