### ISSUE TITLE
Removing a file from within asset manager doesn't remove it from the server.

### ISSUE THREAD

**Issue by LDeeJay1969** [Kruptein/PlanarAlly#229]
When removing a file from asset manager it doesn't delete it from the /assets folder on the server.

**Comment by Kruptein** [comment]
This is currently somewhat intentional.

I've not completely worked out yet how I want file-sharing to work, which could potentially impact how file removal on the server side should behave.

That said, there is no such functionality currently, so we might as well properly remove the file for now.

This should be relatively easy by adding a file removal line to the server/api/socket/asset_manager.py remove function.
