### ISSUE TITLE
Lock backgrounds from accidentally moving the entire map

### ISSUE THREAD

**Issue by Price454** [Kruptein/PlanarAlly#260]
When creating the map layer, I often run into the issue that the background is moved when trying to select overlaying assets such as walls.

is there a way to lock certain assets from moving?
same goes for walls or lines created in the fow layer

**Comment by Kruptein** [comment]
Locking assets is indeed on my list of todo's as well.  The only thing I'm not sure yet about is regarding walls.  Having to manually go over each wall and 'locking' it sounds cumbersome, but locking them by default also doesn't sound great as I often do some minor adjustments alter.  Any ideas what you would like here ?

**Comment by adunis** [comment]
I suggest a keyboard shortcut (something like Ctrl + L) to lock a shape, and also the ability to group select walls and lock them. When group selecting, locked shapes should not be selected (see the user story for the details). If all the group selected shapes are already locked, then select those, this will allow users to 'reset' all the shapes to an unlocked state in two steps. 

(I would suggest also more shortcuts for editing shapes, for example Ctrl + V for toggling 'Blocks vision/light' or Ctrl + M for toggling 'Blocks movement'). 

The user story for someone creating a map with walls would be:

1.  User has the location empty, it either leaves it empty or drags an asset to use as the base layer. It locks the map, either by toggling the option manually or with Ctrl + L. 
2. User starts drawing shapes to use as walls in the empty map or starts drawing 'fow' shapes to put over the walls in the asset used as the base layer. In both cases, when the user has done drawing walls, it group selects all the walls and with Ctrl + L it locks all them. The already locked map should not be selected because it has been already locked. 
3. User does the same for light sources or other assets in the Token layer, and in the in DM layer. 
4. Finally the user starts adding shapes/assets that he doesn't need to be locked, such as 'enemies', that can be easily moved or group selected without the risk of moving or deleting assets that should not be moved during 'play-time', such as FOW shapes. 

IMHO avoiding the risk of deleting assets that should not be deleted at all, especially with the lack of a Ctrl + Z feature, it's a huge improvement of the UX. A further development of this path could prompt the user to 'Confirm' the deletion of an asset if an asset is locked. 

(Assets the should not be deleted easily would be maps or fows the maybe required many minutes to draw)

**Comment by Kruptein** [comment]
Good points all around, that said two remarks:

* Ctrl+v is already occupied as the paste shape keybinding and given that this is a very common interpretation of this keybinding I would like to keep it as such.
* Ideally these keybindings also have a visible UX element or it's going to be a hidden feature only known to a select number of people in most cases.

**Comment by 10leej** [comment]
I like the idea of possibly have a default locked state for things on the map layer with say holding a key like "shift"  to be able to move or resize assets?

**Comment by Price454** [comment]
Default lock state with a modifier to be able to move/re-size is a valid solution.
Another interesting thing would be grouping of objects to allow them to be locked as a group.

**Comment by Kruptein** [comment]
Alright so most work here is done.  You can toggle the locked state of a shape in its properties or with ctrl+L.  Locked shapes cannot be moved/resized.  Groupselection only selects locked shapes if there are no 'normal' shapes in the selection. (the ctrl+L also works on entire selections).

I'm not such a fan of default locked states given that I often do some minor corrections after my initial draw.  What about auto locking shapes on the map/fow layer when you leave the layer.  i.e. you draw some things on the map layer, when you move to the tokens layer the newly created shapes are locked.
