### ISSUE TITLE
Build / Play mode

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/PlanarAlly#261]
I would like to introduce a mode system where you can switch between a build and a play mode.

The shown tools would for example depend on the mode, but also behaviour.  Resizing is for example something that you almost never actually need during play and can easily happen by accident currently.

**Comment by dthv** [comment]
Could this also entail a mode to temporarily suspend token rights? When I improvise an encounter, placing new assets in front of the players, some of them are so eager to engage that they do not wait for me to finish preparation. In these situations, I wish for a "pause" button that freezes the situation / suspends every rights but DM's.

(I suppose "Lock Session" is not what I want? Since I tried and it hat no effect on an ongoing session. Or would I need to file an issue for that, separately, as a bug?)

**Comment by Kruptein** [comment]
Some concept of a pause button for the players could be envisioned in this system sure!

The session lock is more intended for out-of-game moments where you want to lock the session from prying eyes when you prep. (i.e. players should not be able to open the session if it is locked)  It should however also disconnect all players from the session if you toggle it while playing.  If not that is a bug and should be reported separately.  (I do believe it doesn't actually move them to the main screen, but they should not see any updates on the map either)

**Comment by dthv** [comment]
While it's only two clicks away at any time, I wonder whether it would be an improvement for touch-display-users if the Initiative Tool was accessible from the toolbar during Play mode.
