### ISSUE TITLE
[FEAT] bring players accross locations

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#355]
Currently, "bring players" in the context menu affects only players in the present location.
I want to suggest a "bring players (to location)" option as well that does the same what "bring players" does, but also moves players from other locations to the present location.

This is only a small feature usability-wise, as it takes only some clicks to move all players separately. But if it's easy to implement, I would like to see it.

**Comment by Kruptein** [comment]
You can drag the entire player group as one block to a new location, you don't have to drag them individually!

I don't think that I want to add it to the right click menu, just because I don't want to clutter/just have a lot of things in these menus definitely when there is an alternative imo.  wdyt?

**Comment by dthv** [comment]
I wasn't aware of that, sorry. Tested and worked fine. No additional clutter in the context-menu needed!
