### ISSUE TITLE
[BUG] Locations Settings: "Campaign" defaults

### ISSUE THREAD

**Issue by dthv** [Kruptein/PlanarAlly#400]
The Locations settings are a bit inconsistent. First, there are some cosmetic things I'd like to propose. Second, there's a bug with the "Campaign defaults" override check. Third, I think that "campaign defaults" can be misleading and should be re-phrased to say "Session Defaults" (or "Server Defaults"?).

1. Cosmetics
The sentence "Settings that override the campaign defaults are highlighted" are presented differently in the "Grid" and "Vision" preference displays of the Location settings. It should look the same, preferredly like under "Vision".

2. Override Check
Settings overriding defaults are indeed highlighted. If reset to default manually (e.g. by clicking the respective checkbox a second time) does, however, not trigger a re-check for overriding defaults. Thus, a setting actually presenting default values is highlighted as overriding defaults.

3. Campaign vs. Session
What's a campaign, here? In case it refers to a Session, this term should be used. There's a overview over sessions, not campaigns behind the log-in screen. Plus, maybe one campaign is spread over different sessions – in case one might think that "campaign" actually refers to the server.

**Comment by Kruptein** [comment]
1. If they are differently worded then that indeed needs to be streamlined
2. This is intentional design. When dealing with a system with defaults you either reset and follow the default or specify a specific value. It would be impossible to differentiate between a setting that must be enabled even when the default changes at one point without having to do multiple clicks.
3. The correct term would be campaign.  It are settings that persist to the collection of locations that form a campaign together.  In the same manner it should also be Campaign settings and not session settings (as that would imply they are only relevant this particular day you play) and not server settings (as that would imply a global for all campaigns)

**Comment by hmqgg** [comment]
1 has been fixed while doing i18n.

**Comment by dthv** [comment]
They were not differently worded, but differently shown. Just a very, very minor issue, but an issue nontheless.

2. I understand that even if a value actually resembles the default, if set to another value in the past, it is no longer linked to the default value und will stay the current value if the default will change in future. This makes sense, a lot. However, it is not self-explicatory (see me getting it wrong) and should be better explained. Maybe "Reset/link to default" instead of just re-setting?

3. If "campaign" is the correct term to describe a "specific set of locations, assets and settings" (which makes sense, a lot), then probably in the log-in screen "campaign" should be used instead of "session" (e.g. "create new campaign"). Until now, I thought that "specific set of locations, assets and settings" was described as "session" by PA. Hence my misunderstanding.

**Comment by Kruptein** [comment]
I've used session and campaign somewhat interchangeably but they are actually not the same, so yes I'll change it to campaign in the landing page as well.

For your first point, the hover over the reset icon does say 'reset to campaign default' which is in my opinion clear enough.
