### ISSUE TITLE
Blockers for v1.0

### ISSUE THREAD

**Issue by AntiSC2** [Kruptein/PlanarAlly#43]
Was wondering how you are planning to do version numbering in the future. The current one is very simple and straight forward but the next release is 0.9. After that you will reach 1.0 if you don't plan on doing 0.10 etc. Personally in my opinion the 1.0 release should be the first stable release that is somewhat feature complete so it would be nice to keep track of everything in this issue that is blocking v.1.0

**Comment by AntiSC2** [comment]
Issue tracking:

- #44 Proper and visually nice asset management
- #45 Improve initiative tracker
- #46 Default attributes for tokens

**Comment by schemen** [comment]
I could contribute my Docker setup, most up to date here https://github.com/schemen/PlanarAlly/tree/brush

I used the brush branch (worked best for me in terms of usage, better than dev). This has already the new assets system integrated as well.

You can test a running version here: planarally.dndbox.com

**Comment by Kruptein** [comment]
I'll gladly look at your docker setup.

I'm currently doing a large behind the scenes UI overhaul changing stuff from manual dom intersections and jquery to Vue,
hence the slower changes to dev.  But I'm almost done!

Regarding the brush, I've since combined the brush/draw and fow tools in one singular draw tool as can be seen below.  This also means that the brush can be used to draw on normal layers as well :)  (note that this change is currently only in the vue branch)

![image](https://user-images.githubusercontent.com/1814713/44878349-f0d77200-aca6-11e8-9699-671a710383b9.png)

**Comment by schemen** [comment]
Wow, this is amazing!

I would love to contribute my docker/container experience here and I'll be hosting it as well. I may create a second feature request other than the brush ( Basically a slightly stricter sign up policy) :) 

Please let me know once you have the "rougher" changes merged into dev, then I'll see to work on a container around it.

**Comment by Kruptein** [comment]
I've just merged `vue` into `dev` so any feedback on stability and/or usability of dev is much appreciated.

Given that a couple of things still are left to do for the 1.0 milestone, I'm planning on doing a 0.9 release with the new stuff since last release.

**Comment by schemen** [comment]
I have pushed the new docker image onto dndbox: https://planarally.dndbox.com
You can publicly test it there, I'll give you feedback as soon as I get to it as well.

**Comment by Kruptein** [comment]
Given that this has not progressed much, I think I'm gonna close the ticket and re-evaluate what I would like to see done for 1.0
