### ISSUE TITLE
[FEAT] Map Eraser

### ISSUE THREAD

**Issue by ekerstens** [Kruptein/PlanarAlly#619]
**Is your feature request related to a problem? Please describe.**
When using multiple floors, there are times that I want to remove part of the floor to reveal the floor below. For example, if players are fighting in a tavern and blow a hole in the floor, I would want to erase that portion of the map layer to reveal whatever is below. So far as I can tell, it is currently only possible to remove entire assets or objects, rather than to erase/add transparency to a portion. 

**Describe the solution you'd like**
Either an additional build tool or addition to the drawing toolbar adding an eraser tool. From an implementation perspective, this could either mean erasing pixels from the underling object, or adding a mask that adds transparency where the layer/floor has been erased. 

**Describe alternatives you've considered**
I've tried using the hide/reveal functionality of the draw tool, but it looks like these only interact with each other, and can't be used to reveal through other objects on a floor. 

**Additional context**
None.

**Comment by Kruptein** [comment]
Very interesting idea!

**Comment by dthv** [comment]
Indeed a nice idea! Yet, I'm not sure whether this is not slightly out of scope for PA. Maybe it should be done at your local machine with a graphics manipulation programme? The result could be, in future, added as an asset variant (cf. #620 / #163).

Regarding implementation: If possible, I'd prefer masks. In case this isn't possible/feasible (e.g. for reasons of performance etc.), I'd like to propose that editing an asset should actually spawn a copy of said asset so that the asset itself remains untouched. The two could be linked via the new asset variant feature so that a reversal to at least the original state is quick and easy to do.

Regarding the alternative: @ekerstens you're right that the hide/reveal functions of the drawing tool interact only with each other. This is for lighting/vision purposes, cf. (the documentation on lighting/vision)[https://www.planarally.io/docs/dm/light-shadows/#magical-lights-and-darkness]. This should not change.

Last, but not least: Imho, this issue is, at least in parts, connected to #280, #44 and #142.

**Comment by ekerstens** [comment]
What if, rather than modifying single assets, this feature was more like a mask for the whole layer? Returning to the example of blowing a hole in the tavern floor, this could impact multiple assets depending on how the map was created. The ability to flatten a map layer (as suggested in #280) would allow for exporting to another application (GIMP, Photoshop, etc.) for modification, though it would be a pain. What if there was "transparency" draw option which reveals whatever floors are below and layered on top of other assets?

**Comment by Kruptein** [comment]
The way I envision this in a PA context is indeed something that would not touch any of the assets themselves, but simply be an operation on the canvas that makes a certain region transparent for that floor.

This should honestly not be that difficult to implement.

**Comment by Kruptein** [comment]
Check the PR for more info on how it exactly operates!
