### ISSUE TITLE
Find a way to recover from "scrolling away" from the map

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#67]
Hi!

When scrolling out of a map and in again, let's say accidentally  - you have no chance to find the map again as it is basically an infinite canvas.
There should be a way to go back to point 0 or a "deployed assets" view where you can go to said asset.

As a quick report also, I cannot drag&drop maps into the canvas on the latest vue commit

Cheers!

**Comment by Kruptein** [comment]
Hi, this is indeed a very valid problem that I've had happen to me multiple times as well, it's good to have this on the issue tracker as I often forget to work on it ;)

And indeed the drag and drop support was temporarily disabled while I was working on other things but is one of the small amount of items still left to do.

**Comment by schemen** [comment]
Do you have any idea on how to approach this problem? 
Maybe limit the canvas or use a similar approach of "Move player here"  but "move to asset xy"

**Comment by Kruptein** [comment]
I was thinking about introducing a system to mark locations either by right right click or some dedicated tool.   And then giving the ability to jump to these points, and then providing a basic (0, 0) point or something.

Does this sound good for you ?

**Comment by schemen** [comment]
Mh, sounds good, provided a dropped asset would automatically represent a marked locations where you can jump to I guess!

**Comment by Kruptein** [comment]
That would quickly clutter things though.  I would just go with providing the location that you first see when creating a new map as a default 'marked location'.  And giving the option to add some manually.

**Comment by schemen** [comment]
Ah, like a center beacon? And when you create them map there it should be no problem to move back to it?

**Comment by Kruptein** [comment]
Yes indeed.

So you can manually add beacons and go to them at any time.

And on top of that a 'default beacon' should be provided, this could be the center/origin point of the canvas, or could be the very first shape added.

**Comment by schemen** [comment]
Maybe the first object on the map layer serves as initial beacon?

**Comment by LDeeJay1969** [comment]
I found myself in this situation quite a bit (as a noob), so I edited keyboard.ts and added
```
        } else if (event.key === "r" && event.ctrlKey) {
            // Ctrl-r - Re-center/reset the viewport
            gameStore.setPanX(0);
            gameStore.setPanY(0);
            sendClientOptions(gameStore.locationOptions);
            window.location.reload();
```
just below the CTRL-U - event. Now CTRL-R will bring me back to 0,0 where I started from. Probably not the most ideal but just a quick-fix for now until a more elegant solution pops up. I'm thinking of a pop-up list with all placed elements (maybe just a scroll-list of a dump of the 'shape' table) and when one item selected you jump to that location. 

ps. I just post this here because I have no experience with github at all so no clue about forks and pull-requests. If someone can bring me up to speed (or point me to a tutorial) I may be able to help out with some other issues as well (once I get to grips with the PA architecture).

**Comment by Kruptein** [comment]
Hey, thanks for taking a look (and sorry for not providing you with the tools to keep you in position).

You indeed would have to fork my repository, make the changes. commit them to your fork ("version") of the code, and then submit a PR (pull request) on my repository.  There are various tutorials out there, there is also an official github guide I believe, but feel free to message me if things are unclear.

The proposed change is a good thing for now, although I do have some remarks, which I will address if you do make that PR :)

**Comment by LDeeJay1969** [comment]
Just noticed that the solution isn't 'optimal'. The hotkey doesn't jump to the center of the screen (as intended) but to the upper left corner. Will rectify this in another PR.

**Comment by Kruptein** [comment]
The combination of ctrl+0 to go back to the 'spawn' and the markers to jump around should be an initial solution for this issue.

Further down the line we'll probably want to add markers for specific coords instead of shapes and also automatically showing all tokens you own in the marker list as those are typically the important ones.
