### ISSUE TITLE
 [FEAT] Ability to lock/unlock multiple objects at once

### ISSUE THREAD

**Issue by ankorite** [Kruptein/PlanarAlly#710]
Apologies if this is already possible. I would like to be able to select multiple objects and lock/unlock them using the lock icon on the information window on the top right. Currently I have been going to each shape (like my fow walls) and apply the lock to each one individually. This way my not to tech savy co-DM wont accidentally shift or delete the fow walls while opening a door etc.

**Describe alternatives you've considered**
Maybe having a option in the contextual right-click menu to apply things to multiple objects? Or something like the properties window but for everything selected.

Cheers

**Comment by dthv** [comment]
It actually *is* possible via the `Ctrl + L` keybinding (Command instead of Ctrl on Macs since the recent release). Yet, this is not very touch-friendly, so imho this is still a valid feature-request. [See the documentation for more useful keybindings!](https://www.planarally.io/docs/reference/)

I would prefer the properties-window, but applying to everything selected. This would be the most versatile tool while keeping the right-click context-menu clutter-free.

@Kruptein maybe this deserves to be the first issue adorned with a new `touch` label? :slightly_smiling_face:

**Comment by Kruptein** [comment]
As @dthv mentions, there already is _a way_ to lock multiple tokens at once. But indeed this is not touch friendly. Some form of operations on multiple shapes at once has been requested before if I recall. So that's something I'll have to take into account in the near future :)

Make sure your non tech savy friend also knows about the recent undo/redo commands ;)

**Comment by dthv** [comment]
> Some form of operations on multiple shapes at once has been requested before if I recall.

Indeed, cf. #562. Since there's already some discussion on how this should look/feel, maybe this issue should be closed as resolved/duplicate as, technically, @ankorite's request is already implemented in some form and the other forms are already debated.

@ankorite okay for you?

**Comment by ankorite** [comment]
That is perfect, thank you all! Oh, believe me undo/redo where the first hotkeys I showed him.

I am going to close this as the hotkey totally solves my request.
