### ISSUE TITLE
[FEAT] Pan with scroll

### ISSUE THREAD

**Issue by ekerstens** [Kruptein/PlanarAlly#733]
**Is your feature request related to a problem? Please describe.**
When moving tokens, it can be a pain to constantly switch between the pan and select tools. I have seen other tools map panning to scrolling, zoom to +/-, and selection with the mouse. I pan a lot more than I zoom, and it would be great to have a faster and easier way to pan. 

**Describe the solution you'd like**
Ability to pan with the vertical/horizontal scrollbar. Another alternative could potentially be hotkeys to quickly switch between pan and select. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dthv** [comment]
Just to be clear: This is about touch devices, right? Because using your mouse, you can pan with middle-click and hold and using your keyboard it's arrow keys or numpad (the latter also supporting diagonal movement).

I actually don't know whether panning just by clicking *anywhere* on the map is possible to implement, because that would be the most natural thing to do, I think. Yet, I can imagine to have a setting that lets pan-buttons appear when a button in the pan tool is ticked or something.

I'm not sure what you refer to with +/- for zoom, as this does not seem to be for keyboards. Yet, it would indeed be nice to key +/- to zooming.

**Comment by ekerstens** [comment]
I was not aware of the middle-click for pan; I usually use a magic mouse (no middle click) so never discovered that feature. I see now that the docs have a keybindings reference within the quick reference; that is handy. 

The +/- was indeed a separate point referring to the use for keyboards. I've turned off the scroll to zoom feature since I found it finicky. If you'd like, I can close this issue and open a separate one around this.

**Comment by dthv** [comment]
Well, I can imagine a configurable option to set mouse scroll to either pan or scroll. Yet, I wonder how many people actually have two axis on their mouse-wheel? Especially those who don't have a third mouse button…?

**Comment by ekerstens** [comment]
Very good point. The magic mouse is probably pretty unique in that regard.

**Comment by ekerstens** [comment]
Closing in favor of https://github.com/Kruptein/PlanarAlly/issues/736 for zoom keyboard shortcut.
