### ISSUE TITLE
[BUG] Redo doesn't work on mac

### ISSUE THREAD

**Issue by ekerstens** [Kruptein/PlanarAlly#737]
**Describe the bug**
On mac, the keyboard shortcut for redo does not work. `Cmd + shift + z` ignores shift and triggers another undo. 

**To Reproduce**
1. Add a token
2. Move the token twice
3. `Cmd + z` to undo
4. `Cmd + shift + z` to redo, but instead undo happens again.  

**Expected behavior**
Redo should be the opposite of undo. 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: chrome
 - Version 90.0.4430.72 (Official Build) (x86_64)

**Comment by Kruptein** [comment]
I don't own an apple device myself so this one is a bit harder to debug. Do you by any chance use an external keyboard? I see some other issues with cmd+shift in this older thread https://superuser.com/questions/792014/cmd-shift-anything-shortcuts-stopped-working.

Another reason might be that I'm checking for `cmd` and `Z` which on windows automatically includes the shift.
Do you host a version yourself or do you use someone else's version?

If the former I could give you some things to try, otherwise I'll figure out another way to debug it myself

**Comment by ekerstens** [comment]
I do use an external keyboard, though from some quick testing the same also happens using my built in keyboard. I host myself from the docker image, so would be happy to try some things to help debug.
